services:
  - type: web
    name: ai-chatbot-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: GEMINI_API_KEY
        sync: false # Will be set manually in Render dashboard
      - key: MONGODB_URI
        sync: false # Will be set manually in Render dashboard
      - key: CORS_ORIGIN
        sync: false # Will be set manually in Render dashboard
